### ISSUE TITLE
ADGroup one time sync?

### ISSUE THREAD

**Issue by cmille34** [jeremywillans/webex-scripts#1]
First, great job with the Webex_ADGroup_Sync script.  Super well documented and seems to work great with my initial testing.

Not really an issue but more of a question.  We may have a use case where we want to populate Rooms/Spaces with an AD group but if people choose to leave we don't want them pulled back in with the sync script.   Are you aware of any API's to bump against during the sync to see if that user has already left that Room/Space before? 

Thanks for sharing this great script.

**Comment by jeremywillans** [comment]
Hi there!

Glad its useful for you 😄 

From an API perspective, you could use a webhook and subscribe against membership updates, but this would need to be running all the time as it would only fire an event when the user leaves, not necessarily if they have been part of the space before.

The easiest option to implement this would be to maintain a sort of "db" which records an entry each time you add a person to a space, and then load that and check on each cycle? you **could** write an attribute back to AD, but this wouldn't really be scalable if you did this for multiple spaces.

**Comment by cmille34** [comment]
Great suggestions!  After thinking about it more I think I am leaning towards a lazy approach of modifying the script to pull from a separate CSV of the "optional" groups I want to populate with new AD users and simply only pull in AD accounts that have been created in the past 2 days.  That way if they leave the space they won't get pulled back in the next time the script runs.  Thanks again!
